"use strict";
const myPhoneNumber = 126242365;
const myHome = "Dhaka,Bangladesh";
const watchPrice = "25,000TK";
const price1 = 250;
const price2 = 500;
const totalPrice = price1 + price2;
console.log(myPhoneNumber, myHome, "MY Watch Price:", watchPrice);
console.log("Total price of Shopping", totalPrice);
let petName = "Minu the little Arko";
let myAge = 21;
let isMarried = false;
console.log(petName, myAge, isMarried);
petName = 'Dogesh';
console.log(petName);
